### ISSUE TITLE
Ledge catch not working as intended

### ISSUE THREAD

**Issue by Voodoodrood** [Brian-McG/Tempest-Trace#25]
Ledge catch should lower the player and then wait for a command to climb up. Should also be an option to let go of ledge and drop.

**Comment by Brian-McG** [comment]
What is the status of this? Is it going to be resolved?

**Comment by jacquesh** [comment]
Gonna take a look at it later this evening, should be able to get something reasonable done

**Comment by jacquesh** [comment]
Should be working far closer to the expected behaviour now... @Voodoodrood ?

**Comment by Brian-McG** [comment]
I have not noticed any issues thus far.
