### ISSUE TITLE
Vault/ledge climb auto hop

### ISSUE THREAD

**Issue by Voodoodrood** [Brian-McG/Tempest-Trace#36]
In Room 2 where there is the series of boxes  to get up to the walkway run and jump onto the first one and then keep 'w' held down, if you get it right it is possible to get to the third box without doing anything. Feels like the player has no control, is bad. (You have to jump at the right distance so it may take a few tries)

**Comment by Brian-McG** [comment]
What is the status of this? Is it still an issue?

**Comment by jacquesh** [comment]
Well it still happens but I'm probably not going to fix it (although it will be somewhat remedied by a reasonable resolution to #25 )

**Comment by jacquesh** [comment]
It's been somewhat mitigated by reducing the vault height to 50% when you're falling (on top of the implementation of hanging)
