### ISSUE TITLE
Animation state

### ISSUE THREAD

**Issue by Brian-McG** [Brian-McG/Tempest-Trace#47]
![untitled](https://cloud.githubusercontent.com/assets/8310486/9913861/3a5bdeb6-5caf-11e5-9424-f36964bfd116.png)

Playing the climb animation once you already up most of the wall doesn't look so good.
Its probably unlikely we can fix this for upcoming demo but should be fixed for final release.

**Comment by jacquesh** [comment]
I've modified the path taken while climbing to make this look significantly better (it no longer climbs vertically and then horizontally, now takes a more direct/diagonal route)
I don't think we're ever going to get this perfect but it looks much better now I think.
Let me know what you guys think

**Comment by jacquesh** [comment]
Apparently you think its fine, so I'm closing
