### ISSUE TITLE
Lightmap artefacts

### ISSUE THREAD

**Issue by Brian-McG** [Brian-McG/Tempest-Trace#71]
![untitled](https://cloud.githubusercontent.com/assets/8310486/10337946/75970ff0-6d03-11e5-9c0a-03fe0a0db626.png)
![untitled](https://cloud.githubusercontent.com/assets/8310486/10337961/8e550be6-6d03-11e5-8ecc-af5df4b16ffd.png)
![untitled](https://cloud.githubusercontent.com/assets/8310486/10337973/a5f14b5c-6d03-11e5-8f74-f1d54ff19fd6.png)

**Comment by jacquesh** [comment]
If we can't fix these can we at least avoid them in the intro (I only watched the intro once...if these don't appear then ignore me)

**Comment by Brian-McG** [comment]
I don't want to change the intro path since getting the end timing correct is difficult. 
Is there a way to just disable lightmaps for intro?

**Comment by jacquesh** [comment]
No well its not a massive problem, but if it were easy to change the intro path then I'd do that, if (as you say) it isnt...then just leave it, its fine
