### ISSUE TITLE
Vault animation occasionally does not trigger

### ISSUE THREAD

**Issue by Brian-McG** [Brian-McG/Tempest-Trace#72]
I cannot pin-point the exact cause but have seen this on a number of occasions now.
I have seen it on the first obstacle from time to time.

**Comment by jacquesh** [comment]
Can't seem to reproduce this...please let me know if anybody can (even remotely) consistently reproduce this? =/

**Comment by Brian-McG** [comment]
I have been able to reproduce this.
*For first obstacle*
It seems you have to run into the obstacle at a slow speed then try vault.
