### ISSUE TITLE
Smoke Bomb Issues

### ISSUE THREAD

**Issue by jacquesh** [Brian-McG/Tempest-Trace#74]
If I use a smokebomb and then die, I should probably respawn with the ability to use that smoke bomb again.
Possibly clear any existing smoke bombs when the player dies as well? I dunno.

**Comment by Brian-McG** [comment]
I do not agree, what I do think is that the 'Smoke Shield' should be applied immediately when the player uses a smoke bomb not when the bomb explodes (as it currently is).

**Comment by Brian-McG** [comment]
Let me know if 2d2b21510995837569f588b3abcd01a23efe0885 has caused any artefacts or issues
