### ISSUE TITLE
Smoke bomb will not deploy due to thin geometry (Training Level)

### ISSUE THREAD

**Issue by Brian-McG** [Brian-McG/Tempest-Trace#78]
On the training level the geometry is too thin, the smoke bomb does not trigger.

The geometry needs to be made thicker.

**Comment by Voodoodrood** [comment]
While this is partially because of thin geometry, I also noticed that smoke bombs do not trigger on mesh colliders, which are used in for the cylinder building in the training level as well as the bowl building in the main game.

**Comment by Brian-McG** [comment]
Interesting, will take a look.

**Comment by Brian-McG** [comment]
I changed the implementation a bit to resolve this issue, drawback is that the smoke bomb is static when it reaches its deploy location. If for example that platform is moving the bomb will deploy at the position the platform was at when the bomb was thrown.

It should only affect elevator.
The issue is fixable but I am not sure if it is worth fixing or not.
