### ISSUE TITLE
Occlusion Culling

### ISSUE THREAD

**Issue by jacquesh** [Brian-McG/Tempest-Trace#79]
Mostly putting this here so I don't forget. It just occurred to me (when I tried to run the game on highest graphics settings and it dropped to ~40fps from 60 on my laptop) that since almost our entire world is static, we should be able to get pretty good performance benefits from setting up occlusion culling (I mean think about it...if you're in passage you may as well only render the passage because you can't see anything else anyways)

**Comment by Brian-McG** [comment]
I gave this a quick try (it calculates very fast) using the default paramaters and it more than doubled the frame rate and reduced the draw calls at the start location by about 4-5 times.
